version: '3.8'

services:
  router:
    build:
      context: .
      dockerfile: ./router/Dockerfile
    container_name: router
    volumes:
      - ./shared_data:/shared_data
    network_mode: host

  webserv:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    container_name: WebServer
    mac_address: "AA:BB:CC:DD:EE:05"
    networks:
      UBHNet:
        ipv4_address: 10.42.0.5
    ports:
      - "8080:8080"
    volumes:
      - ./shared_data:/shared_data

  filesystem_challenge:
    build:
      context: . # todo: change 
      dockerfile: ./filesystem_challenge/Dockerfile
    container_name: file_host
    mac_address: "AA:BB:CC:DD:EE:06"
    networks:
      UBHNet:
        ipv4_address: 10.42.0.6
    ports:
      - "9000:9000"

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: database
    mac_address: "AA:BB:CC:DD:EE:15"
    networks:
      UBHNet:
        ipv4_address: 10.42.0.15
    ports:
      - "3306:3306" # expose dfaul port
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script
    
networks:
  UBHNet:
    name: ubh-net
    ipam:
      config:
        - subnet: 10.42.0.0/24