version: '3.8'

services:
  router:
    build:
      context: .
      dockerfile: ./router/Dockerfile
    container_name: router
    volumes:
      - ./shared_data:/shared_data
    network_mode: host

  webserv:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    container_name: WebServer
    mac_address: "AA:BB:CC:DD:EE:05"
    networks:
      UBHNet:
        ipv4_address: 10.42.0.5
    ports:
      - "8080:8080"
    volumes:
      - ./shared_data:/shared_data

  filesystem_challenge:
    build:
      context: .
      dockerfile: ./filesystem_challenge/Dockerfile
    container_name: file_host
    mac_address: "AA:BB:CC:DD:EE:06"
    networks:
      UBHNet:
        ipv4_address: 10.42.0.6
    
networks:
  UBHNet:
    name: ubh-net
    ipam:
      config:
        - subnet: 10.42.0.0/24